### ISSUE TITLE
[next] HTML example material needs fixing

### ISSUE THREAD

**Issue by DefinitelyMaybe** [threlte/threlte#1101]
In the [next docs](https://next.threlte.xyz/docs/reference/extras/html), the html example doesn't appear to have the color or text updated on click.

**Comment by grischaerbe** [comment]
This actually uncovered a larger problem with the current architecture of having a wrapping element surrounding the `<canvas>` to be able to attach stuff to it. Turns out the `<OrbitControls>` attach themselves to the `renderer.domElement.parentElement`, so the wrapping element, which seems fine at first. It turns out that the [`THREE.OrbitControls` capture the pointer](https://github.com/mrdoob/three.js/blob/37d6f280a5cd642e801469bb048f52300d31258e/examples/jsm/controls/OrbitControls.js#L1122) thus preventing any following pointer events from firing, such as the `click` event on the `<HTML>` contents. I'll make a follow up issue on that one, we'll have to think about a solution for that. For now, the HTML example is fixed in #1127  :)
