### ISSUE TITLE
`svelte-check`errors with getting started scene

### ISSUE THREAD

**Issue by shot-codes** [threlte/threlte#181]
Hi. I've got the threlte 5 getting started 'First Scene' (https://threlte.xyz/getting-started#first-scene) up and running in a skeleton Sveltekit application. upon running `svelte-check` I see the following errors

```
   21:20  error   Identifier expected. ​js:1003
   21:47  error   Unexpected token. Did you mean `{'>'}` or `&gt;`? ​js:1382
   32:6   error   Expected corresponding JSX closing tag for 'T.Group'. ​js:17002
   33:5   error   Expected corresponding JSX closing tag for 'Canvas'. ​js:17002
   36:33  error   Identifier expected. ​js:1003
   36:51  error   Unexpected token. Did you mean `{'>'}` or `&gt;`? ​js:1382
   39:5   error   Expected corresponding JSX closing tag for 'div'. ​js:17002
   40:4   error   Expected corresponding closing tag for JSX fragment. ​js:17015
   41:1   error   ')' expected. ​js:1005
   21:12  error   Type 'true' is not assignable to type 'number | [x: number, y: number, z: number] | undefined'. ​js:2322
   36:25  error   Type 'true' is not assignable to type 'number | [x: number, y: number, z: number, order?: EulerOrder | undefined] | undefined'. ​js:2322
   41:3   error   Cannot find name 'div'. ​js:2304
```

**Comment by dant4301** [comment]
i got a vaguely similar **svelte-check error** when I changed the position and rotation parameters passed in the Getting started example from: position.y={0.5}
to:
position={[0, 0.5, 0]}
Thought it might be of some relevance here.

**Comment by grischaerbe** [comment]
From Discord:
"I've just had an insightful conversation with Simon (dummdidumm, Svelte core maintainer) about our problem of dot-notation for props. `svelte2tsx` will not be dropped for the next major version of `svelte-check` which is in fact the backbone also of the Svelte VS Code Extension. But the fact that the extension does not error out on dot-notation props while just running `svelte-check` does is because the extension by default uses the flag `--use-new-transformation` which allows for dot notation props. The next version of `svelte-check` will also default to that, for now just apply the flag manually: svelte-check `--use-new-transformation`".
