### ISSUE TITLE
Weird bug on Chrome using Linux

### ISSUE THREAD

**Issue by cristovao-trevisan** [threlte/threlte#252]
Hello. I found a weird bug that happens on ArchLinux (at least) using Chrome. The screen flickers and movement seems dragged.

Brave and Firefox do not have this bug. Also works on Windows (Chrome included). I'm using a i5-1135G7 (with Intel TigerLake-LP GT2 [Iris Xe Graphics] GPU) , but it also happens on my old i3 (6th gen).

Curiosly only the arcade example works. Other libraries also seem to work fine (tested svelte-cubed and react-three-fiber). 

https://user-images.githubusercontent.com/4981855/211649458-cb142932-50de-4fcf-9056-5478117b6d62.mp4

**Comment by grischaerbe** [comment]
Hey @cristovao-trevisan, this is an interesting one. I have no idea where to start, the colors seem odd as well. Other examples don't work as well but the arcade example does? The arcade example uses a different rendering pipeline, but all other ones use the standard three.js `WebGLRenderer`, so there should not be any problems, especially since you tested other libraries relying on that as well.
I'd like to dig a bit deeper but i have the feeling this is not library-related. Feel free to join our [Discord server](https://discord.gg/EqUBCfCaGm) so we can investigate your problem.

**Comment by cristovao-trevisan** [comment]
Knowning that the renderer is the problem I just tried it's configs and setting `powerPreference` to 'default' or 'low-power' removes the bug. The problem is probably related to the GPU driver, but I'm happy I got a fix.

Should [high-performance](https://github.com/threlte/threlte/blob/f1cf4c9d55dc90cea861dbc9988ac67c67f24e0a/packages/core/src/lib/lib/renderer.ts#L20) be the default instead of 'default'?
