### ISSUE TITLE
Threlte Color management obsolete?

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#57]
Beginning with Version R139 of three.js it includes a maybe better but definitely different color management by opt-in: https://threejs.org/docs/#manual/en/introduction/Color-management

This might make threltes color management obsolete but it definitely needs a thorough look.

**Comment by grischaerbe** [comment]
This might also fix the color differences in #87

**Comment by donmccurdy** [comment]
The effect of THREE.ColorManagement, when enabled, is that hexadecimal and CSS colors are interpreted as sRGB by default, and converted automatically to Linear-sRGB (which otherwise needs to be done manually). Because all colors in HTML, CSS, and most color pickers are sRGB, this is a helpful convention for developers and designers. The THREE.Color RGB components, and other methods of accessing them, remain Linear-sRGB as before. There's a similar distinction between hexadecimal and RGB colors in Blender.

Fog, background, and WebGL clear color should also behave more predictably in this mode; without it they are special cases the user must know about and convert.

I'd recommend using THREE. ColorManagement in a new framework like threlte, but there's one major caveat to be aware of — it needs to be enabled *before* initializing colors, or it won't affect them.
