### ISSUE TITLE
THREE example types fail for projects using `moduleResolution: "bundler"`

### ISSUE THREAD

**Issue by sxxov** [threlte/threlte#617]
Hi, firstly thank every one of you for this wonderful project.

## Explanation

When using TypeScript with the config `moduleResolution: "bundler"`, some of the types will resolve to `any`.

<img width="659" alt="image" src="https://github.com/threlte/threlte/assets/50891910/f513247c-6ecf-4d82-a7e6-9d2670d30728">

This is due to a combination of the usage of `three/examples/jsm/*` with no extension at the end (i.e. `three/examples/jsm/loaders/GLTFLoader` instead of `three/examples/jsm/loaders/GLTFLoader.js`), & the difference of resolution between `"bundler"` (the current recommended standard) & `"node"` (the config used by this project).

Adding '.js' to the end of the `d.ts` manually,

<img width="611" alt="image" src="https://github.com/threlte/threlte/assets/50891910/131ba7bc-fa1b-442f-9c5e-85fe29b9b4dc">

 ...resolves the issue:

<img width="662" alt="image" src="https://github.com/threlte/threlte/assets/50891910/4d744fb8-276f-4505-9ce1-ba5c127dd636">

## Repro

1. Set `moduleResolution: "bundler"` in `tsconfig.json`
2. Create the following file:
```svelte
<script lang="ts">
  import { useGltf } from '@threlte/extras';

  const gltf = useGltf<{ nodes: {}, materials: {} }>('/amogus.glb');
     // ^ AsyncWritable<any>
</script>
```

## Solution

If it's okay with the maintainers, I propose the library to ship with `.js` at the end of these imports to support every one using `"bundler"` whilst maintaining `"node"` compatibility.

**Comment by grischaerbe** [comment]
Hi @Sxxov, good catch. If there are no downsides to adding file extensions, I'm completely fine with it. Do you mind making a PR?

**Comment by Sxxov** [comment]
OK! Some questions about the scope of the PR though.

1. Should I only replace `three/examples/jsm/*` with a '.js' extension? This issue will still happen if you using anything `three/*`, & I see many usages of `three/src/math/MathUtils` (instead of `import { MathUtils } from 'three';`)
2. How would we ensure future usages follow this '.js' convention?
3. Should this project use `"bundler"` too? It would solve 2. but would require all usages `three/*` to have the '.js' extension.

**Comment by grischaerbe** [comment]
[Fixed](https://github.com/threlte/threlte/pull/618#issuecomment-1738682403)
