### ISSUE TITLE
Load GLTF-File twice

### ISSUE THREAD

**Issue by LukasLoeffler** [threlte/threlte#632]
Hello together, thanks for the greate project its a pleasure to work with Threlte,

I have issues loading the same exact GLTF file twice.

```
<GLTF
    position={[10, 10, 10]}
    url="/static/<FILE_TO_LOAD>.gltf"
/>

<GLTF
    position={[20, 20 , 20]}
    url="/static/<FILE_TO_LOAD>.gltf"
/>
```

Loading two different GLTF-Files works as expected and both models are shown. However, if the same model is loaded twice, only the second model is displayed.

I think the 'issue', if one can speak of one, lies in ThreeJS itself as described in this thread: [use-the-same-gltf-model-twice-in-react-three-fiber-drei-three-js](https://stackoverflow.com/questions/68813736/use-the-same-gltf-model-twice-in-react-three-fiber-drei-three-js)

My question is how to handle such issues the "Threlte-Way"?

**Comment by selenecodes** [comment]
This might be interesting to you: https://threlte.xyz/docs/reference/extras/instanced-mesh.
Allows you to show multiple instances of the same model and also saves on performance.

**Comment by grischaerbe** [comment]
Hi @LukasLoeffler, this is indeed expected behaviour. A glTF file loaded via `<GLTF>` under the hood uses the hook `useLoader(GLTFLoader)` which caches the model being loaded by an identifier, in this case the prop `url` passed to `<GLTF>`. So having two components `<GLTF>` in your scene with the same `url` indeed will give you *one* model because a single `THREE.Object3D` can only be in one place at a time in your scene. So why is this cached? glTF files are inherently large and expensive to parse. This is the reason the utility [`@threlte/gltf`](https://threlte.xyz/docs/reference/gltf/getting-started) exists: The utility is reusing the stuff that is actually reusable (geometries, materials) and instantiates the rest (Meshes, Groups, everything that extends `THREE.Object3D`).

There's a workaround however: You can pass a different `url` `<GLTF>` by adding a search parameter, which tricks the cache into thinking it's not present:

```svelte
<GLTF
    position={[10, 10, 10]}
    url="/static/<FILE_TO_LOAD>.gltf"
/>

<GLTF
    position={[20, 20 , 20]}
    url="/static/<FILE_TO_LOAD>.gltf?a"
/>
```

I would not suggest to do that however. The file in question will eventually be loaded twice over the network (~browser cache layer) and parsed twice (definitely). Another way to have mutliple copies of the same glTF model is by utilizing [`<InstancedMeshes>`](https://threlte.xyz/docs/reference/extras/instanced-meshes).

**Comment by LukasLoeffler** [comment]
Sorry for this late reply.
@grischaerbe Thanks for this detailed clarification and the tip for the workaround.
I will test the instanced mesh in the future and give feedback.

**Comment by awarebayes** [comment]
'''jsx
<InstancedMesh>
	<PersonModel scale={0.009} />
	<Instance position.x={-2} position.y={0} />
	<Instance position.x={-2} position.y={1} />
</InstancedMesh>
'''

Uncaught TypeError: Cannot read properties of null (reading 'boundingSphere')

I think it tries to calculate bounding sphere at first render and it cant because the model is not loaded yet

**Comment by awarebayes** [comment]
[localhost-1702488040668.log](https://github.com/threlte/threlte/files/13663713/localhost-1702488040668.log)
