### ISSUE TITLE
Types don't work in new projects anymore

### ISSUE THREAD

**Issue by enyo** [threlte/threlte#835]
Reproduce:

```
# Create a new project
npm create svelte@latest my-app
cd my-app
pnpm i

# Add threlte dependency
pnpm add -D @threlte/extras
```

Open the `+page.svelte` file and add this:

```html
<script lang="ts">
  import type {  ThrelteGltf } from '@threlte/extras'
  const foo: ThrelteGltf<any>
</script>
```

And you'll see that `foo` has the type `any`.

This is because the types for `@threlte/extras` are defined like this:

```ts
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import type { SceneGraph } from '../lib/buildSceneGraph';
/**
 * Extends THREE.GLTF by materials and nodes properties
 */
export type ThrelteGltf<Graph extends SceneGraph> = GLTF & Graph;
```

and I think that for some reason the `.js` extension is now required, so the GLTF import should look like this:

```ts
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
```

**Comment by DefinitelyMaybe** [comment]
> ```
> <script lang="ts">
>   import type {  ThrelteGltf } from '@threlte/extras'
>   const foo: ThrelteGltf<any>
> </script>
> ```

probably dumb question but why do you need the `<any>` within your `const foo: ThrelteGltf<any>` statement?

**Comment by enyo** [comment]
> > ```
> > <script lang="ts">
> >   import type {  ThrelteGltf } from '@threlte/extras'
> >   const foo: ThrelteGltf<any>
> > </script>
> > ```
> 
> probably dumb question but why do you need the `<any>` within your `const foo: ThrelteGltf<any>` statement?

Normally I have a proper type there but it was not necessary to show the error so I just replaced with any

**Comment by DefinitelyMaybe** [comment]
Ok so there's a couple of things to be mindful of here before going further,

1. `pnpm add -D @threlte/extras` holds a bunch of components that don't make sense without `@threlte/core`, but not wrong per se here because in your setup your only using types.
2. `const foo: ThrelteGltf<any>` is an incomplete statement. The type error I'm getting at that point is `'const' declarations must be initialized.`.

**Comment by m4nh** [comment]
Maybe is related to this issue. If i try to build a new sveltekit project only with the OrbitControls examples found in:

https://threlte.xyz/docs/reference/extras/orbit-controls

The 
```
npm run dev
```

works. But:

```
npm run build
npm run preview
```

is not working. Because OrbitControls is not found with:

```
code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:/ <project_root> /node_modules/three/examples/jsm/controls/OrbitControls'
```

Installing @types/three also does not resolve the problem.

The issue is with all adapters (auto, node, static etc.).
Maybe i'm missing some build configuration?
Thanks
